export const LOGIN_USER = "USER_LOGIN";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESSFULL";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const ADD_INSPECTION_REPORT = "ADD_INSPECTION_REPORT";
export const ADD_INSPECTION_REPORT_SUCCESS = "ADD_INSPECTION_REPORT_SUCCESS"

export const INSPECTION_REPORT = "INSPECTION_REPORT";
export const INSPECTION_REPORT_SUCCESS = "INSPECTION_REPORT_SUCCESS";

export const COMMENT_DETAILS = "COMMENT_DETAILS";
export const COMMENT_DETAILS_SUCCESS = "COMMENT_DETAILS_SUCCESS";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
